import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--model', type=str, default='FAST', help='which model to run')
parser.add_argument('--mode', type=str, default='train', help='debug to run')  # train or test
parser.add_argument('--debug', type=eval, default=False, help='debug to run')  # if not add log
parser.add_argument('--dataset', type=str, choices=['METRLA', 'PEMSBAY', 'PEMS08', 'PEMS04'], default='PEMS04', help='which dataset to run')
parser.add_argument('--dataset_dir', type=str, default='../../datasets/PEMS04/processed/', help='which dataset to run')
parser.add_argument('--train_ratio', type=float, default=0.6, help='the ratio of training and validation data among the total')
parser.add_argument('--val_ratio', type=float, default=0.2, help='the ratio of validation data among the trainval ratio')
parser.add_argument('--num_nodes', type=int, default=307, help='num_nodes')
parser.add_argument('--seq_len', type=int, default=12, help='input sequence length')
parser.add_argument('--horizon', type=int, default=12, help='output sequence length')
parser.add_argument('--input_dim', type=int, default=3, help='number of input channel')
parser.add_argument('--output_dim', type=int, default=1, help='number of output channel')
parser.add_argument('--num_layers', type=int, default=3, help='num_layers')
parser.add_argument('--num_experts', type=int, default=8, help='num_experts')
parser.add_argument('--num_agents', type=int, default=32, help='num_agents')
parser.add_argument('--hidden_dim', type=int, default=64, help='hidden_dim')
parser.add_argument('--time_of_day_size', type=int, default=288, help='time_of_day_size')
parser.add_argument('--day_of_week_size', type=int, default=7, help='day_of_week_size')

parser.add_argument("--epochs", type=int, default=200, help="number of epochs of training")
parser.add_argument('--loss_func', type=str, default="masked_mae", help='loss function')
parser.add_argument('--grad_norm', type=eval, default=True, help='grad norm')
parser.add_argument('--max_grad_norm', type=int, default=5, help='max grad norm')
parser.add_argument("--early_stop", type=eval, default=True, help="number of early_stop of training")
parser.add_argument("--early_stop_patience", type=int, default=30, help="patience used for early stop")
parser.add_argument("--batch_size", type=int, default=64, help="size of the batches")
parser.add_argument("--lr", type=float, default=0.002, help="base learning rate")
parser.add_argument("--weight_decay", type=float, default=0.0001, help="weight decay")
parser.add_argument("--milestones", type=eval, default=[10, 20, 30, 40, 50], help="milestones")
parser.add_argument("--gamma", type=float, default=0.5, help="gamma")
parser.add_argument('--device', type=str, default="cuda:0", help='which gpu to use')
parser.add_argument('--seed', type=int, default=233, help='random seed.')
args = parser.parse_args()